<a href="https://colab.research.google.com/github/Prabhu-2004-04/Deep-Learning/blob/main/MatrixTr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
import numpy as np
x_data=[[1,2],[2,3]]
x_data=torch.tensor(x_data)
print(x_data)
y_data=np.array([[14,42],[25,78]])
y_data=torch.from_numpy(y_data)
print(y_data)

tensor([[1, 2],
        [2, 3]])
tensor([[14, 42],
        [25, 78]])


In [12]:

z_data = [[1, 2, 3], [4, 5, 6],[3,6,8]]
z_data = torch.tensor(z_data)
print(z_data)

tensor([[1, 2, 3],
        [4, 5, 6],
        [3, 6, 8]])
